import { IPaginatedResponse } from "@/types/IPaginatedResult";
import { ITVShow, ITVDetail } from "@/types/ITVShow";

export const tv_shows: ITVShow[] = [
  {
    adult: false,
    backdrop_path: "/pj1wFbZF3gpEg7F0EreXTvZNZTG.jpg",
    id: 110492,
    name: "Peacemaker",
    original_name: "Peacemaker",
    overview:
      "The continuing story of Peacemaker, a vainglorious superhero/supervillain who believes in peace at any cost — no matter how many people he has to kill. After a miraculous recovery from his duel with Bloodsport, Peacemaker soon discovers that his freedom comes at a price.",
    poster_path: "/yb4F1Oocq8GfQt6iIuAgYEBokhG.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10759, 10765, 18],
    popularity: 142.703,
    first_air_date: "2022-01-13",
    vote_average: 8.246,
    vote_count: 2879,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/25g7mthXoJFcNZhAKz0evk17Bsx.jpg",
    id: 157239,
    name: "Alien: Earth",
    original_name: "Alien: Earth",
    overview:
      "When the mysterious deep space research vessel USCSS Maginot crash-lands on Earth, Wendy and a ragtag group of tactical soldiers make a fateful discovery that puts them face-to-face with the planet's greatest threat.",
    poster_path: "/yueXS3q8BtoWekcHOATFHicLl3e.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10765, 18],
    popularity: 334.9768,
    first_air_date: "2025-08-12",
    vote_average: 7.8,
    vote_count: 232,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/9QwPn3hV58ESYzT6YbWPzGJ9SjG.jpg",
    id: 280945,
    name: "Bon Appétit, Your Majesty",
    original_name: "폭군의 셰프",
    overview:
      "After time traveling to the Joseon era, a talented chef meets a tyrant king. Her modern dishes captivate his palate, but royal challenges await her.",
    poster_path: "/exUXEOierAwZ597010TLQka9TFy.jpg",
    media_type: "tv",
    original_language: "ko",
    genre_ids: [10765, 18],
    popularity: 16.2513,
    first_air_date: "2025-08-23",
    vote_average: 7,
    vote_count: 2,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/6fRwRD7GdCfg6owzmCT3VgQtowl.jpg",
    id: 37854,
    name: "One Piece",
    original_name: "ワンピース",
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
    media_type: "tv",
    original_language: "ja",
    genre_ids: [10759, 35, 16],
    popularity: 25.9978,
    first_air_date: "1999-10-20",
    vote_average: 8.722,
    vote_count: 4969,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/UI2S7dJdGylqp9xK3GwRt7zz68.jpg",
    id: 259909,
    name: "Dexter: Resurrection",
    original_name: "Dexter: Resurrection",
    overview:
      "Dexter Morgan awakens from a coma to find Harrison gone without a trace. Realizing the weight of what he put his son through, Dexter sets out for New York City, determined to find him and make things right. But closure won't come easy. When Miami Metro's Angel Batista arrives with questions, Dexter realizes his past is catching up to him fast. As father and son navigate their own darkness in the city that never sleeps, they soon find themselves deeper than they ever imagined - and that the only way out is together.",
    poster_path: "/hIawSocuwqgNeRf3JuKuxgMHmSC.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [80, 18],
    popularity: 87.891,
    first_air_date: "2025-07-13",
    vote_average: 8.942,
    vote_count: 146,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/wBEAtmYwsmXbIw9czMSJ9iyxV3w.jpg",
    id: 240558,
    name: "King & Conqueror",
    original_name: "King & Conqueror",
    overview:
      "The story of a clash that defined the future of a country and a continent for a thousand years. Harold of Wessex and William of Normandy were two men destined to meet at the Battle of Hastings in 1066. These two former allies with no design on the British throne found themselves forced by circumstance and personal obsession into a war for possession of its crown.",
    poster_path: "/3sFiQAnpWbimSWXLCUCQOUtCoy7.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [18, 10759],
    popularity: 4.5599,
    first_air_date: "2025-08-24",
    vote_average: 0,
    vote_count: 0,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/mcU5nwUqPJB6GeElDhKA68LKhqD.jpg",
    id: 253372,
    name: "The Institute",
    original_name: "The Institute",
    overview:
      "When 14 year old genius Luke Ellis is kidnapped, he awakens at The Institute, a facility full of children who all got there the same way he did, and who are all possessed of unusual abilities. In a nearby town, haunted former police officer Tim Jamieson has come looking to start a new life, but the peace and quiet won’t last, as his story and Luke’s are destined to collide.",
    poster_path: "/7JXZdWifaa6wL0XLRi0GJOlOA8y.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [9648, 10765],
    popularity: 38.3817,
    first_air_date: "2025-07-13",
    vote_average: 7.962,
    vote_count: 52,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/i9IEOD1Li1y89xRHKH9kiE8dt9z.jpg",
    id: 127235,
    name: "Invasion",
    original_name: "Invasion",
    overview:
      "Earth is visited by an alien species that threatens humanity's existence. Events unfold in real time through the eyes of five ordinary people across the globe as they struggle to make sense of the chaos unraveling around them.",
    poster_path: "/xP4SIyOn7vUh0OqT4a30MHhNFMO.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10765, 18],
    popularity: 77.0857,
    first_air_date: "2021-10-21",
    vote_average: 7.149,
    vote_count: 1029,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 126.9428,
    first_air_date: "2011-04-17",
    vote_average: 8.5,
    vote_count: 25410,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qg8Gv2w0dDL8cMsG2QO2hWp58wy.jpg",
    id: 119051,
    name: "Wednesday",
    original_name: "Wednesday",
    overview:
      "Smart, sarcastic and a little dead inside, Wednesday Addams investigates twisted mysteries while making new friends — and foes — at Nevermore Academy.",
    poster_path: "/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10765, 9648, 35],
    popularity: 391.7456,
    first_air_date: "2022-11-23",
    vote_average: 8.403,
    vote_count: 9492,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/9DrORnlwnjt5SeJKcuE5sqOoIdV.jpg",
    id: 207468,
    name: "Kaiju No. 8",
    original_name: "怪獣８号",
    overview:
      "In a world plagued by creatures known as Kaiju, Kafka Hibino aspired to enlist in The Defense Force. He makes a promise to enlist with his childhood friend, Mina Ashiro. Soon, life takes them in separate ways. While employed cleaning up after Kaiju battles, Kafka meets Reno Ichikawa. Reno's determination to join The Defense Force reawakens Kafka's promise to join Mina and protect humanity.",
    poster_path: "/bJxGs0w5RAhaX4fIUQu511rvm0S.jpg",
    media_type: "tv",
    original_language: "ja",
    genre_ids: [16, 10759, 10765],
    popularity: 90.9779,
    first_air_date: "2024-04-13",
    vote_average: 8.552,
    vote_count: 599,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/8jppViW8aKsaLyj8tLFEYJdc7Sa.jpg",
    id: 253093,
    name: "Shadow Love",
    original_name: "与晋长安",
    overview:
      "General Li Shuang of Taijin finds a man who has lost his memory and names him Jin An. Jin An devotes himself to accompanying Li Shuang; however, as he gradually regains his memories, he discovers that he is actually a prince from an enemy nation. Once bound by love, the two are forced into battle. Together, they confront challenges that test their loyalties and beliefs, striving to resolve the conflict and uphold the justice they both believe in.",
    poster_path: "/qOxfpvyXtbV31ruLIAYAtxfu4OW.jpg",
    media_type: "tv",
    original_language: "zh",
    genre_ids: [18],
    popularity: 4.8891,
    first_air_date: "2025-08-24",
    vote_average: 0,
    vote_count: 0,
    origin_country: ["CN"],
  },
  {
    adult: false,
    backdrop_path: "/mPsf0GVm115YOrNn0EyLnqPRpcv.jpg",
    id: 248937,
    name: "Hostage",
    original_name: "Hostage",
    overview:
      "When the British prime minister's husband is kidnapped and the French president starts receiving threats, both leaders must face an impossible choice.",
    poster_path: "/r8nC8ZKOVWq8bqTF7AMLQI6NgM8.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [18, 10768],
    popularity: 84.0618,
    first_air_date: "2025-08-21",
    vote_average: 6.2,
    vote_count: 15,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/Kl07j8DsHfAwkODBblg81mjcGc.jpg",
    id: 229958,
    name: "Aema",
    original_name: "애마",
    overview:
      'In 1980s Korea, a movie star and a starlet defy male-dominated industry rules and backstage corruption while filming the provocative "Madame Aema."',
    poster_path: "/jD8uwm1fvt6y2yxjSO6R9IOFwQQ.jpg",
    media_type: "tv",
    original_language: "ko",
    genre_ids: [18, 35],
    popularity: 19.9881,
    first_air_date: "2025-08-22",
    vote_average: 8.6,
    vote_count: 5,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/tj74qN7hRxIWTtypkqXPfmAvpop.jpg",
    id: 272485,
    name: "This Thriving Land",
    original_name: "生万物",
    overview:
      "On her wedding day, Ning Xiuxiu, the daughter of Tianqiang Temple Village's richest man, is kidnapped by bandits. Her father refuses to pay the ransom, marrying her sister to her childhood sweetheart instead. In defiance, Xiuxiu cuts ties with her family and marries farmer Feng Dajiao, learning the value of land and community. Inspired by revolutionary ideals, she empowers village women to challenge feudal beliefs and leads efforts against banditry and the Japanese invasion.",
    poster_path: "/svQ4AsJLwFxlNw9hRWo8Bi2UvJG.jpg",
    media_type: "tv",
    original_language: "zh",
    genre_ids: [18],
    popularity: 18.4809,
    first_air_date: "2025-08-13",
    vote_average: 9,
    vote_count: 2,
    origin_country: ["CN"],
  },
  {
    adult: false,
    backdrop_path: "/vmNj8bthBAofXgsaY6yP4bCvXko.jpg",
    id: 93740,
    name: "Foundation",
    original_name: "Foundation",
    overview:
      "Follow a band of exiles on their monumental journey to save humanity and rebuild civilization amid the fall of the Galactic Empire.",
    poster_path: "/tg9I5pOY4M9CKj8U0cxVBTsm5eh.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10765, 18],
    popularity: 77.1168,
    first_air_date: "2021-09-23",
    vote_average: 7.8,
    vote_count: 1466,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/kWByUrGgS4mYyvQ2mG95gzblBOj.jpg",
    id: 106449,
    name: "A Record of a Mortal's Journey to Immortality",
    original_name: "凡人修仙传",
    overview:
      "A poor and ordinary boy from a village joins a minor sect in Jiang Hu and becomes an Unofficial Disciple by chance. How will Han Li, a commoner by birth, establish a foothold for himself in his sect? With his mediocre aptitude, he must successfully traverse the treacherous path of cultivation and avoid the notice of those who may do him harm. This is a story of an ordinary mortal who, against all odds, clashes with devilish demons and ancient celestials in order to find his own path towards immortality.",
    poster_path: "/3m1UaMLgmpj6krNaQwTpftYFsnz.jpg",
    media_type: "tv",
    original_language: "zh",
    genre_ids: [16, 10759, 10765],
    popularity: 57.5341,
    first_air_date: "2020-07-25",
    vote_average: 8.4,
    vote_count: 59,
    origin_country: ["CN"],
  },
  {
    adult: false,
    backdrop_path: "/ppfObQ9676tl5xA87WDdSLZa7yC.jpg",
    id: 274875,
    name: "Twelve",
    original_name: "트웰브",
    overview:
      "A group of heroes, each embodying one of the 12 zodiac signs, battles to defend the Korean Peninsula from malevolent spirits.",
    poster_path: "/6q66Psq2cDrCsoz8cGDVa6gFmMm.jpg",
    media_type: "tv",
    original_language: "ko",
    genre_ids: [10765, 10759, 18],
    popularity: 13.0997,
    first_air_date: "2025-08-23",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/uNTrRKIOyKYISthoeizghtXPEOK.jpg",
    id: 240411,
    name: "Dan Da Dan",
    original_name: "ダンダダン",
    overview:
      "In a bet to prove whether ghosts or aliens exist, two high schoolers face terrifying paranormal threats, gain superpowers and maybe even fall in love?!",
    poster_path: "/6qfZAOEUFIrbUH3JvePclx1nXzz.jpg",
    media_type: "tv",
    original_language: "ja",
    genre_ids: [16, 10759, 35, 10765],
    popularity: 95.8612,
    first_air_date: "2024-10-04",
    vote_average: 8.646,
    vote_count: 618,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/uvSEjgc4vKWefFC6nWBCTQ22UwF.jpg",
    id: 227114,
    name: "Butterfly",
    original_name: "Butterfly",
    overview:
      "David Jung, a mysterious former US intelligence operative living in hiding in South Korea, has his life blown to pieces when the consequences of an impossible decision from his past come back to haunt him, and he finds himself hunted by Rebecca, a deadly young assassin, and Caddis, the sinister spy organization she works for.",
    poster_path: "/8x1W0TR2VIe7ORaRI9zwDqeJn9q.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10759, 18],
    popularity: 100.8469,
    first_air_date: "2025-08-13",
    vote_average: 7.647,
    vote_count: 51,
    origin_country: ["US"],
  },
];

export const paginated_tv_shows: IPaginatedResponse<ITVShow> = {
  page: 1,
  results: tv_shows,
  total_pages: 500,
  total_results: 10000,
};

export const tv_detail: ITVDetail = {
  adult: false,
  backdrop_path: "/pj1wFbZF3gpEg7F0EreXTvZNZTG.jpg",
  created_by: [
    {
      id: 15218,
      credit_id: "5fb532d73a48c5003f855998",
      name: "James Gunn",
      original_name: "James Gunn",
      gender: 2,
      profile_path: "/pnKqZub3IlKYbyH9RRTMDOoqEn0.jpg",
    },
  ],
  episode_run_time: [],
  first_air_date: "2022-01-13",
  genres: [
    {
      id: 10759,
      name: "Action & Adventure",
    },
    {
      id: 10765,
      name: "Sci-Fi & Fantasy",
    },
    {
      id: 18,
      name: "Drama",
    },
  ],
  homepage: "https://www.hbomax.com/shows/peacemaker-2022/a939d96b-7ffb-4481-96f6-472838d104ca",
  id: 110492,
  in_production: true,
  languages: ["en"],
  last_air_date: "2025-08-28",
  last_episode_to_air: {
    id: 6209411,
    name: "A Man Is Only As Good As His Bird",
    overview:
      "As Economos clashes with his new handler, Peacemaker must deal with the consequences of his actions in the alternate dimension.",
    vote_average: 8.045,
    vote_count: 11,
    air_date: "2025-08-28",
    episode_number: 2,
    episode_type: "standard",
    production_code: "202",
    runtime: 51,
    season_number: 2,
    show_id: 110492,
    still_path: "/sAqQYYUMaS9FqHNACCQL9LRwsYn.jpg",
  },
  name: "Peacemaker",
  next_episode_to_air: {
    id: 6209412,
    name: "Another Rick Up My Sleeve",
    overview: "",
    vote_average: 0,
    vote_count: 0,
    air_date: "2025-09-04",
    episode_number: 3,
    episode_type: "standard",
    production_code: "",
    runtime: null,
    season_number: 2,
    show_id: 110492,
    still_path: null,
  },
  networks: [
    {
      id: 3186,
      logo_path: "/nmU0UMDJB3dRRQSTUqawzF2Od1a.png",
      name: "HBO Max",
      origin_country: "",
    },
    {
      id: 8304,
      logo_path: "/gqWI9y0owo9sxgzZD7TXOeILYI9.png",
      name: "HBO Max",
      origin_country: "",
    },
  ],
  number_of_episodes: 16,
  number_of_seasons: 2,
  origin_country: ["US"],
  original_language: "en",
  original_name: "Peacemaker",
  overview:
    "The continuing story of Peacemaker, a vainglorious superhero/supervillain who believes in peace at any cost — no matter how many people he has to kill. After a miraculous recovery from his duel with Bloodsport, Peacemaker soon discovers that his freedom comes at a price.",
  popularity: 274.3664,
  poster_path: "/yb4F1Oocq8GfQt6iIuAgYEBokhG.jpg",
  production_companies: [
    {
      id: 1957,
      logo_path: "/pJJw98MtNFC9cHn3o15G7vaUnnX.png",
      name: "Warner Bros. Television",
      origin_country: "US",
    },
    {
      id: 11565,
      logo_path: "/odU3l6csuBmXUrzFm6araUgEUHQ.png",
      name: "The Safran Company",
      origin_country: "US",
    },
    {
      id: 94218,
      logo_path: "/kxuhS8wyKtVprOn5nckdHyNuSg1.png",
      name: "Troll Court Entertainment",
      origin_country: "US",
    },
    {
      id: 184898,
      logo_path: "/2Z2hiM1ERqFOWRxNxWoJZ8lTxhb.png",
      name: "DC Studios",
      origin_country: "US",
    },
    {
      id: 429,
      logo_path: "/4Y00XuSMuP1gimd0jP6JT57QbCI.png",
      name: "DC",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  seasons: [
    {
      air_date: "2022-11-21",
      episode_count: 3,
      id: 322663,
      name: "Specials",
      overview: "",
      poster_path: "/gds3teCjWRX4nQDnchSYq6zW167.jpg",
      season_number: 0,
      vote_average: 0,
    },
    {
      air_date: "2022-01-13",
      episode_count: 8,
      id: 163789,
      name: "Season 1",
      overview:
        "After surviving being shot and then buried beneath a collapsing building, Peacemaker returns home only to realize that his freedom comes at a price. He is now part of Amanda Waller's new team fighting a mysterious new threat. Can he eliminate the threat without making things worse?",
      poster_path: "/hE3LRZAY84fG19a18pzpkZERjTE.jpg",
      season_number: 1,
      vote_average: 7.5,
    },
    {
      air_date: "2025-08-21",
      episode_count: 8,
      id: 427669,
      name: "Season 2",
      overview:
        "Following the exposure of Project Butterfly and the disbandment of Task Force X, the 11th Street Kids grapple with new identities, new friendships, and new rivalries. For Peacemaker, this means reconciling his past with his newfound sense of purpose — here and in an alternate dimension. Meanwhile, Rick Flag Sr. reappears as the director of A.R.G.U.S., focused on controlling metahumans and avenging the death of his son at the hands of Peacemaker.",
      poster_path: "/yb4F1Oocq8GfQt6iIuAgYEBokhG.jpg",
      season_number: 2,
      vote_average: 8.2,
    },
  ],
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Returning Series",
  tagline: "In what world are they the heroes?",
  type: "Scripted",
  vote_average: 8.2,
  vote_count: 2917,
};
