name: Run Migrations

on:
  push:
    paths:
      - "drizzle/**"
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  push-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Push Drizzle migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run drizzle:push
